spring:
  jpa:
    # Best practice: it permits avoiding database access after the end of the transaction
    open-in-view: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      # Best practice to avoid problems by managing update explicitly
      ddl-auto: none
  sql:
    init:
      # Best practice to not modifying the database at the application start
      mode: never
  liquibase:
    change-log: classpath:/db/changelog/db.changelog-root.yaml